// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.vrsim_messages
{
    public class StudyStepResultMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new StudyStepResultMsg(msg);
            });
        }

        #endregion

        public uint step;
        public bool hasError;
        public string message;

        public const string _ROS_MESSAGE_ID = "vrsim_messages/StudyStepResult";

        public StudyStepResultMsg(uint step = 0, bool hasError = false, string message = "") : base()
        {
            this.step = step;
            this.hasError = hasError;
            this.message = message;
        }

        public StudyStepResultMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddUInt(this.step);
            message.AddBool(this.hasError);
            message.AddString(this.message);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.step = message.GetUInt();
            this.hasError = message.GetBool();
            this.message = message.GetString();
        }

        #endregion
    }
}
