// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class AccelMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new AccelMsg(msg);
            });
        }

        #endregion

        public Vector3Msg linear;
        public Vector3Msg angular;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Accel";

        public AccelMsg(Vector3Msg linear = null, Vector3Msg angular = null) : base()
        {
            this.linear = linear;
            this.angular = angular;
        }

        public AccelMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.linear.serializeToMessage(message, includeHeader: false);
            this.angular.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.linear = new Vector3Msg();
            this.linear.deserializeFromMessage(message);
            this.angular = new Vector3Msg();
            this.angular.deserializeFromMessage(message);
        }

        #endregion
    }
}
