// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class InertiaMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new InertiaMsg(msg);
            });
        }

        #endregion

        public double m;
        public Vector3Msg com;
        public double ixx;
        public double ixy;
        public double ixz;
        public double iyy;
        public double iyz;
        public double izz;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Inertia";

        public InertiaMsg(double m = 0, Vector3Msg com = null, double ixx = 0, double ixy = 0, double ixz = 0, double iyy = 0, double iyz = 0, double izz = 0) : base()
        {
            this.m = m;
            this.com = com;
            this.ixx = ixx;
            this.ixy = ixy;
            this.ixz = ixz;
            this.iyy = iyy;
            this.iyz = iyz;
            this.izz = izz;
        }

        public InertiaMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddDouble(this.m);
            this.com.serializeToMessage(message, includeHeader: false);
            message.AddDouble(this.ixx);
            message.AddDouble(this.ixy);
            message.AddDouble(this.ixz);
            message.AddDouble(this.iyy);
            message.AddDouble(this.iyz);
            message.AddDouble(this.izz);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.m = message.GetDouble();
            this.com = new Vector3Msg();
            this.com.deserializeFromMessage(message);
            this.ixx = message.GetDouble();
            this.ixy = message.GetDouble();
            this.ixz = message.GetDouble();
            this.iyy = message.GetDouble();
            this.iyz = message.GetDouble();
            this.izz = message.GetDouble();
        }

        #endregion
    }
}
