// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.geometry_msgs
{
    public class Point32Msg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new Point32Msg(msg);
            });
        }

        #endregion

        public float x;
        public float y;
        public float z;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Point32";

        public Point32Msg(float x = 0f, float y = 0f, float z = 0f) : base()
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public Point32Msg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddFloat(this.x);
            message.AddFloat(this.y);
            message.AddFloat(this.z);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.x = message.GetFloat();
            this.y = message.GetFloat();
            this.z = message.GetFloat();
        }

        #endregion
    }
}
