// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class PoseMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new PoseMsg(msg);
            });
        }

        #endregion

        public PointMsg position;
        public QuaternionMsg orientation;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Pose";

        public PoseMsg(PointMsg position = null, QuaternionMsg orientation = null) : base()
        {
            this.position = position;
            this.orientation = orientation;
        }

        public PoseMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.position.serializeToMessage(message, includeHeader: false);
            this.orientation.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.position = new PointMsg();
            this.position.deserializeFromMessage(message);
            this.orientation = new QuaternionMsg();
            this.orientation.deserializeFromMessage(message);
        }

        #endregion
    }
}
