// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.geometry_msgs
{
    public class Pose2DMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new Pose2DMsg(msg);
            });
        }

        #endregion

        public double x;
        public double y;
        public double theta;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Pose2D";

        public Pose2DMsg(double x = 0, double y = 0, double theta = 0) : base()
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
        }

        public Pose2DMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddDouble(this.x);
            message.AddDouble(this.y);
            message.AddDouble(this.theta);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.x = message.GetDouble();
            this.y = message.GetDouble();
            this.theta = message.GetDouble();
        }

        #endregion
    }
}
