// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class TransformMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TransformMessage(msg);
            });
        }

        #endregion

        public Vector3Message translation;
        public QuaternionMessage rotation;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Transform";

        public TransformMessage(Vector3Message translation = null, QuaternionMessage rotation = null) : base()
        {
            this.translation = translation;
            this.rotation = rotation;
        }

        public TransformMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            this.translation.serializeToMessage(message);
            this.rotation.serializeToMessage(message);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.translation = new Vector3Message();
            this.translation.deserializeFromMessage(message);
            this.rotation = new QuaternionMessage();
            this.rotation.deserializeFromMessage(message);
        }

        #endregion
    }
}
