// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;
using ros_messages.std_msgs;

namespace ros_messages.geometry_msgs
{
    public class TransformStampedMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TransformStampedMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public string child_frame_id;
        public TransformMsg transform;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/TransformStamped";

        public TransformStampedMsg(HeaderMsg header = null, string child_frame_id = "", TransformMsg transform = null) : base()
        {
            this.header = header;
            this.child_frame_id = child_frame_id;
            this.transform = transform;
        }

        public TransformStampedMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddString(this.child_frame_id);
            this.transform.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.child_frame_id = message.GetString();
            this.transform = new TransformMsg();
            this.transform.deserializeFromMessage(message);
        }

        #endregion
    }
}
