// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class TransformMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TransformMsg(msg);
            });
        }

        #endregion

        public Vector3Msg translation;
        public QuaternionMsg rotation;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Transform";

        public TransformMsg(Vector3Msg translation = null, QuaternionMsg rotation = null) : base()
        {
            this.translation = translation;
            this.rotation = rotation;
        }

        public TransformMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.translation.serializeToMessage(message, includeHeader: false);
            this.rotation.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.translation = new Vector3Msg();
            this.translation.deserializeFromMessage(message);
            this.rotation = new QuaternionMsg();
            this.rotation.deserializeFromMessage(message);
        }

        #endregion
    }
}
