// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class TwistWithCovarianceMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TwistWithCovarianceMsg(msg);
            });
        }

        #endregion

        public TwistMsg twist;
        public double[] covariance;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/TwistWithCovariance";

        public TwistWithCovarianceMsg(TwistMsg twist = null, double[] covariance = null) : base()
        {
            this.twist = twist;
            this.covariance = covariance;
        }

        public TwistWithCovarianceMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.twist.serializeToMessage(message, includeHeader: false);
            message.AddDoubles(this.covariance, false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.twist = new TwistMsg();
            this.twist.deserializeFromMessage(message);
            message.GetDoubles(36, this.covariance);
        }

        #endregion
    }
}
