// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;
using ros_messages.std_msgs;

namespace ros_messages.geometry_msgs
{
    public class Vector3StampedMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new Vector3StampedMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public Vector3Msg vector;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Vector3Stamped";

        public Vector3StampedMsg(HeaderMsg header = null, Vector3Msg vector = null) : base()
        {
            this.header = header;
            this.vector = vector;
        }

        public Vector3StampedMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            this.vector.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.vector = new Vector3Msg();
            this.vector.deserializeFromMessage(message);
        }

        #endregion
    }
}
