// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.geometry_msgs;

namespace ros_messages.geometry_msgs
{
    public class WrenchMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new WrenchMsg(msg);
            });
        }

        #endregion

        public Vector3Msg force;
        public Vector3Msg torque;

        public const string _ROS_MESSAGE_ID = "geometry_msgs/Wrench";

        public WrenchMsg(Vector3Msg force = null, Vector3Msg torque = null) : base()
        {
            this.force = force;
            this.torque = torque;
        }

        public WrenchMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.force.serializeToMessage(message, includeHeader: false);
            this.torque.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.force = new Vector3Msg();
            this.force.deserializeFromMessage(message);
            this.torque = new Vector3Msg();
            this.torque.deserializeFromMessage(message);
        }

        #endregion
    }
}
