// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.trajectory_msgs;
using ros_messages.std_msgs;

namespace ros_messages.control_msgs
{
    public class JointTrajectoryControllerStateMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new JointTrajectoryControllerStateMessage(msg);
            });
        }

        #endregion

        public HeaderMessage header;
        public List<string> joint_names;
        public JointTrajectoryPointMessage desired;
        public JointTrajectoryPointMessage actual;
        public JointTrajectoryPointMessage error;

        public const string _ROS_MESSAGE_ID = "control_msgs/JointTrajectoryControllerState";

        public JointTrajectoryControllerStateMessage(HeaderMessage header = null, List<string> joint_names = null, JointTrajectoryPointMessage desired = null, JointTrajectoryPointMessage actual = null, JointTrajectoryPointMessage error = null) : base()
        {
            this.header = header;
            this.joint_names = joint_names;
            this.desired = desired;
            this.actual = actual;
            this.error = error;
        }

        public JointTrajectoryControllerStateMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            this.header.serializeToMessage(message);
            message.AddStrings(this.joint_names.ToArray());
            this.desired.serializeToMessage(message);
            this.actual.serializeToMessage(message);
            this.error.serializeToMessage(message);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMessage();
            this.header.deserializeFromMessage(message);
            this.joint_names = new List<string>(message.GetStrings());
            this.desired = new JointTrajectoryPointMessage();
            this.desired.deserializeFromMessage(message);
            this.actual = new JointTrajectoryPointMessage();
            this.actual.deserializeFromMessage(message);
            this.error = new JointTrajectoryPointMessage();
            this.error.deserializeFromMessage(message);
        }

        #endregion
    }
}
