// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.sensor_msgs;
using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class CameraInfoMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new CameraInfoMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public uint height;
        public uint width;
        public string distortion_model;
        public List<double> D;
        public double[] K;
        public double[] R;
        public double[] P;
        public uint binning_x;
        public uint binning_y;
        public RegionOfInterestMsg roi;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/CameraInfo";

        public CameraInfoMsg(HeaderMsg header = null, uint height = 0, uint width = 0, string distortion_model = "", List<double> D = null, double[] K = null, double[] R = null, double[] P = null, uint binning_x = 0, uint binning_y = 0, RegionOfInterestMsg roi = null) : base()
        {
            this.header = header;
            this.height = height;
            this.width = width;
            this.distortion_model = distortion_model;
            this.D = D;
            this.K = K;
            this.R = R;
            this.P = P;
            this.binning_x = binning_x;
            this.binning_y = binning_y;
            this.roi = roi;
        }

        public CameraInfoMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddUInt(this.height);
            message.AddUInt(this.width);
            message.AddString(this.distortion_model);
            message.AddDoubles(this.D.ToArray());
            message.AddDoubles(this.K, false);
            message.AddDoubles(this.R, false);
            message.AddDoubles(this.P, false);
            message.AddUInt(this.binning_x);
            message.AddUInt(this.binning_y);
            this.roi.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.height = message.GetUInt();
            this.width = message.GetUInt();
            this.distortion_model = message.GetString();
            this.D = new List<double>(message.GetDoubles());
            message.GetDoubles(9, this.K);
            message.GetDoubles(9, this.R);
            message.GetDoubles(12, this.P);
            this.binning_x = message.GetUInt();
            this.binning_y = message.GetUInt();
            this.roi = new RegionOfInterestMsg();
            this.roi.deserializeFromMessage(message);
        }

        #endregion
    }
}
