// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class CompressedImageMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new CompressedImageMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public string format;
        public List<byte> data;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/CompressedImage";

        public CompressedImageMsg(HeaderMsg header = null, string format = "", List<byte> data = null) : base()
        {
            this.header = header;
            this.format = format;
            this.data = data;
        }

        public CompressedImageMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddString(this.format);
            message.AddBytes(this.data.ToArray());
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.format = message.GetString();
            this.data = new List<byte>(message.GetBytes());
        }

        #endregion
    }
}
