// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class IlluminanceMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new IlluminanceMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public double illuminance;
        public double variance;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/Illuminance";

        public IlluminanceMsg(HeaderMsg header = null, double illuminance = 0, double variance = 0) : base()
        {
            this.header = header;
            this.illuminance = illuminance;
            this.variance = variance;
        }

        public IlluminanceMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddDouble(this.illuminance);
            message.AddDouble(this.variance);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.illuminance = message.GetDouble();
            this.variance = message.GetDouble();
        }

        #endregion
    }
}
