// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class JointStateMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new JointStateMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public List<string> name;
        public List<double> position;
        public List<double> velocity;
        public List<double> effort;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/JointState";

        public JointStateMsg(HeaderMsg header = null, List<string> name = null, List<double> position = null, List<double> velocity = null, List<double> effort = null) : base()
        {
            this.header = header;
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
        }

        public JointStateMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddStrings(this.name.ToArray());
            message.AddDoubles(this.position.ToArray());
            message.AddDoubles(this.velocity.ToArray());
            message.AddDoubles(this.effort.ToArray());
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.name = new List<string>(message.GetStrings());
            this.position = new List<double>(message.GetDoubles());
            this.velocity = new List<double>(message.GetDoubles());
            this.effort = new List<double>(message.GetDoubles());
        }

        #endregion
    }
}
