// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class JoyMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new JoyMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public List<float> axes;
        public List<int> buttons;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/Joy";

        public JoyMsg(HeaderMsg header = null, List<float> axes = null, List<int> buttons = null) : base()
        {
            this.header = header;
            this.axes = axes;
            this.buttons = buttons;
        }

        public JoyMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddFloats(this.axes.ToArray());
            message.AddInts(this.buttons.ToArray());
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.axes = new List<float>(message.GetFloats());
            this.buttons = new List<int>(message.GetInts());
        }

        #endregion
    }
}
