// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class JoyFeedbackMsg : ROSMessage
    {

        public const byte TYPE_LED = 0;
        public const byte TYPE_RUMBLE = 1;
        public const byte TYPE_BUZZER = 2;

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new JoyFeedbackMsg(msg);
            });
        }

        #endregion

        public byte type;
        public byte id;
        public float intensity;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/JoyFeedback";

        public JoyFeedbackMsg(byte type = 0, byte id = 0, float intensity = 0f) : base()
        {
            this.type = type;
            this.id = id;
            this.intensity = intensity;
        }

        public JoyFeedbackMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddByte(this.type);
            message.AddByte(this.id);
            message.AddFloat(this.intensity);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.type = message.GetByte();
            this.id = message.GetByte();
            this.intensity = message.GetFloat();
        }

        #endregion
    }
}
