// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class LaserEchoMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new LaserEchoMsg(msg);
            });
        }

        #endregion

        public List<float> echoes;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/LaserEcho";

        public LaserEchoMsg(List<float> echoes = null) : base()
        {
            this.echoes = echoes;
        }

        public LaserEchoMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddFloats(this.echoes.ToArray());
        }

        public override void deserializeFromMessage(Message message)
        {
            this.echoes = new List<float>(message.GetFloats());
        }

        #endregion
    }
}
