// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class NavSatStatusMsg : ROSMessage
    {

        public const sbyte STATUS_NO_FIX = -1;
        public const sbyte STATUS_FIX = 0;
        public const sbyte STATUS_SBAS_FIX = 1;
        public const sbyte STATUS_GBAS_FIX = 2;
        public const ushort SERVICE_GPS = 1;
        public const ushort SERVICE_GLONASS = 2;
        public const ushort SERVICE_COMPASS = 4;
        public const ushort SERVICE_GALILEO = 8;

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new NavSatStatusMsg(msg);
            });
        }

        #endregion

        public sbyte status;
        public ushort service;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/NavSatStatus";

        public NavSatStatusMsg(sbyte status = 0, ushort service = 0) : base()
        {
            this.status = status;
            this.service = service;
        }

        public NavSatStatusMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddSByte(this.status);
            message.AddUShort(this.service);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.status = message.GetSByte();
            this.service = message.GetUShort();
        }

        #endregion
    }
}
