// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.sensor_msgs;
using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class NavSatFixMsg : ROSMessage
    {

        public const byte COVARIANCE_TYPE_UNKNOWN = 0;
        public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
        public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        public const byte COVARIANCE_TYPE_KNOWN = 3;

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new NavSatFixMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public NavSatStatusMsg status;
        public double latitude;
        public double longitude;
        public double altitude;
        public double[] position_covariance;
        public byte position_covariance_type;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/NavSatFix";

        public NavSatFixMsg(HeaderMsg header = null, NavSatStatusMsg status = null, double latitude = 0, double longitude = 0, double altitude = 0, double[] position_covariance = null, byte position_covariance_type = 0) : base()
        {
            this.header = header;
            this.status = status;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.position_covariance = position_covariance;
            this.position_covariance_type = position_covariance_type;
        }

        public NavSatFixMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            this.status.serializeToMessage(message, includeHeader: false);
            message.AddDouble(this.latitude);
            message.AddDouble(this.longitude);
            message.AddDouble(this.altitude);
            message.AddDoubles(this.position_covariance, false);
            message.AddByte(this.position_covariance_type);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.status = new NavSatStatusMsg();
            this.status.deserializeFromMessage(message);
            this.latitude = message.GetDouble();
            this.longitude = message.GetDouble();
            this.altitude = message.GetDouble();
            message.GetDoubles(9, this.position_covariance);
            this.position_covariance_type = message.GetByte();
        }

        #endregion
    }
}
