// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class PointFieldMsg : ROSMessage
    {

        public const byte INT8 = 1;
        public const byte UINT8 = 2;
        public const byte INT16 = 3;
        public const byte UINT16 = 4;
        public const byte INT32 = 5;
        public const byte UINT32 = 6;
        public const byte FLOAT32 = 7;
        public const byte FLOAT64 = 8;

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new PointFieldMsg(msg);
            });
        }

        #endregion

        public string name;
        public uint offset;
        public byte datatype;
        public uint count;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/PointField";

        public PointFieldMsg(string name = "", uint offset = 0, byte datatype = 0, uint count = 0) : base()
        {
            this.name = name;
            this.offset = offset;
            this.datatype = datatype;
            this.count = count;
        }

        public PointFieldMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddString(this.name);
            message.AddUInt(this.offset);
            message.AddByte(this.datatype);
            message.AddUInt(this.count);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.name = message.GetString();
            this.offset = message.GetUInt();
            this.datatype = message.GetByte();
            this.count = message.GetUInt();
        }

        #endregion
    }
}
