// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class RegionOfInterestMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new RegionOfInterestMsg(msg);
            });
        }

        #endregion

        public uint x_offset;
        public uint y_offset;
        public uint height;
        public uint width;
        public bool do_rectify;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/RegionOfInterest";

        public RegionOfInterestMsg(uint x_offset = 0, uint y_offset = 0, uint height = 0, uint width = 0, bool do_rectify = false) : base()
        {
            this.x_offset = x_offset;
            this.y_offset = y_offset;
            this.height = height;
            this.width = width;
            this.do_rectify = do_rectify;
        }

        public RegionOfInterestMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddUInt(this.x_offset);
            message.AddUInt(this.y_offset);
            message.AddUInt(this.height);
            message.AddUInt(this.width);
            message.AddBool(this.do_rectify);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.x_offset = message.GetUInt();
            this.y_offset = message.GetUInt();
            this.height = message.GetUInt();
            this.width = message.GetUInt();
            this.do_rectify = message.GetBool();
        }

        #endregion
    }
}
