// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.sensor_msgs
{
    public class SetCameraInfoResponseMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new SetCameraInfoResponseMsg(msg);
            });
        }

        #endregion

        public bool success;
        public string status_message;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/SetCameraInfoResponse";

        public SetCameraInfoResponseMsg(bool success = false, string status_message = "") : base()
        {
            this.success = success;
            this.status_message = status_message;
        }

        public SetCameraInfoResponseMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddBool(this.success);
            message.AddString(this.status_message);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.success = message.GetBool();
            this.status_message = message.GetString();
        }

        #endregion
    }
}
