// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.sensor_msgs;

namespace ros_messages.sensor_msgs
{
    public class SetCameraInfoRequestMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new SetCameraInfoRequestMsg(msg);
            });
        }

        #endregion

        public CameraInfoMsg camera_info;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/SetCameraInfoRequest";

        public SetCameraInfoRequestMsg(CameraInfoMsg camera_info = null) : base()
        {
            this.camera_info = camera_info;
        }

        public SetCameraInfoRequestMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.camera_info.serializeToMessage(message, includeHeader: false);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.camera_info = new CameraInfoMsg();
            this.camera_info.deserializeFromMessage(message);
        }

        #endregion
    }
}
