// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.sensor_msgs
{
    public class TimeReferenceMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TimeReferenceMsg(msg);
            });
        }

        #endregion

        public HeaderMsg header;
        public uint[] time_ref;
        public string source;

        public const string _ROS_MESSAGE_ID = "sensor_msgs/TimeReference";

        public TimeReferenceMsg(HeaderMsg header = null, uint[] time_ref = null, string source = "") : base()
        {
            this.header = header;
            this.time_ref = time_ref;
            this.source = source;
        }

        public TimeReferenceMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.header.serializeToMessage(message, includeHeader: false);
            message.AddUInt(this.time_ref[0]);
            message.AddUInt(this.time_ref[1]);
            message.AddString(this.source);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.header = new HeaderMsg();
            this.header.deserializeFromMessage(message);
            this.time_ref = new uint[]{message.GetUInt(), message.GetUInt()};
            this.source = message.GetString();
        }

        #endregion
    }
}
