// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class DurationMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new DurationMessage(msg);
            });
        }

        #endregion

        public int[] data;

        public const string _ROS_MESSAGE_ID = "std_msgs/Duration";

        public DurationMessage(int[] data = null) : base()
        {
            this.data = data;
        }

        public DurationMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            message.AddInt(this.data[0]);
            message.AddInt(this.data[1]);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.data = new int[]{message.GetInt(), message.GetInt()};
        }

        #endregion
    }
}
