// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class HeaderMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new HeaderMessage(msg);
            });
        }

        #endregion

        public uint seq;
        public uint[] stamp;
        public string frame_id;

        public const string _ROS_MESSAGE_ID = "std_msgs/Header";

        public HeaderMessage(uint seq = 0, uint[] stamp = null, string frame_id = "") : base()
        {
            this.seq = seq;
            this.stamp = stamp;
            this.frame_id = frame_id;
        }

        public HeaderMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            message.AddUInt(this.seq);
            message.AddUInt(this.stamp[0]);
            message.AddUInt(this.stamp[1]);
            message.AddString(this.frame_id);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.seq = message.GetUInt();
            this.stamp = new uint[]{message.GetUInt(), message.GetUInt()};
            this.frame_id = message.GetString();
        }

        #endregion
    }
}
