// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;

using ros_messages.std_msgs;

namespace ros_messages.std_msgs
{
    public class Int32MultiArrayMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new Int32MultiArrayMsg(msg);
            });
        }

        #endregion

        public MultiArrayLayoutMsg layout;
        public List<int> data;

        public const string _ROS_MESSAGE_ID = "std_msgs/Int32MultiArray";

        public Int32MultiArrayMsg(MultiArrayLayoutMsg layout = null, List<int> data = null) : base()
        {
            this.layout = layout;
            this.data = data;
        }

        public Int32MultiArrayMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            this.layout.serializeToMessage(message, includeHeader: false);
            message.AddInts(this.data.ToArray());
        }

        public override void deserializeFromMessage(Message message)
        {
            this.layout = new MultiArrayLayoutMsg();
            this.layout.deserializeFromMessage(message);
            this.data = new List<int>(message.GetInts());
        }

        #endregion
    }
}
