// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class Int32Msg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new Int32Msg(msg);
            });
        }

        #endregion

        public int data;

        public const string _ROS_MESSAGE_ID = "std_msgs/Int32";

        public Int32Msg(int data = 0) : base()
        {
            this.data = data;
        }

        public Int32Msg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddInt(this.data);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.data = message.GetInt();
        }

        #endregion
    }
}
