// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class MultiArrayDimensionMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new MultiArrayDimensionMessage(msg);
            });
        }

        #endregion

        public string label;
        public uint size;
        public uint stride;

        public const string _ROS_MESSAGE_ID = "std_msgs/MultiArrayDimension";

        public MultiArrayDimensionMessage(string label = "", uint size = 0, uint stride = 0) : base()
        {
            this.label = label;
            this.size = size;
            this.stride = stride;
        }

        public MultiArrayDimensionMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            message.AddString(this.label);
            message.AddUInt(this.size);
            message.AddUInt(this.stride);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.label = message.GetString();
            this.size = message.GetUInt();
            this.stride = message.GetUInt();
        }

        #endregion
    }
}
