// generated by RosbridgeMessageGenerator
// generated on 22 May 2025, 00:29:59

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class TimeMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TimeMsg(msg);
            });
        }

        #endregion

        public uint[] data;

        public const string _ROS_MESSAGE_ID = "std_msgs/Time";

        public TimeMsg(uint[] data = null) : base()
        {
            this.data = data;
        }

        public TimeMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddUInt(this.data[0]);
            message.AddUInt(this.data[1]);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.data = new uint[]{message.GetUInt(), message.GetUInt()};
        }

        #endregion
    }
}
