// generated by RosbridgeMessageGenerator
// generated on 02 Aug 2023, 02:53:51

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.std_msgs
{
    public class TimeMessage : ROSMessage
    {

        

        #region Registration
        
#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new TimeMessage(msg);
            });
        }

        #endregion

        public uint[] data;

        public const string _ROS_MESSAGE_ID = "std_msgs/Time";

        public TimeMessage(uint[] data = null) : base()
        {
            this.data = data;
        }

        public TimeMessage(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message)
        {
            message.AddString(_ROS_MESSAGE_ID);
            message.AddUInt(this.data[0]);
            message.AddUInt(this.data[1]);
        }

        public override void deserializeFromMessage(Message message)
        {
            this.data = new uint[]{message.GetUInt(), message.GetUInt()};
        }

        #endregion
    }
}
