// generated by RosbridgeMessageGenerator
// generated on 27 May 2025, 04:17:01

using System;
using System.Collections.Generic;

using Riptide;
using Visus.Robotics.RosBridge;



namespace ros_messages.shape_msgs
{
    public class MeshTriangleMsg : ROSMessage
    {

        

        #region Registration

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void _registerMessage () {
            ROSMessageFactory.registerMessage(_ROS_MESSAGE_ID, delegate(Message msg)
            {
                return new MeshTriangleMsg(msg);
            });
        }

        #endregion

        public uint[] vertex_indices;

        public const string _ROS_MESSAGE_ID = "shape_msgs/MeshTriangle";

        public MeshTriangleMsg(uint[] vertex_indices = null) : base()
        {
            this.vertex_indices = vertex_indices;
        }

        public MeshTriangleMsg(Message message) : base()
        {
            this.deserializeFromMessage(message);
        }


        #region Serialization

        public override void serializeToMessage(Message message, bool includeHeader = true)
        {
            if (includeHeader) {
                message.AddString(_ROS_MESSAGE_ID);
            }
            message.AddUInts(this.vertex_indices, false);
        }

        public override void deserializeFromMessage(Message message)
        {
            message.GetUInts(3, this.vertex_indices);
        }

        #endregion
    }
}
